### ISSUE TITLE
No makefile found

### ISSUE THREAD

**Issue by JoshFialkoff** [troglodyne/iContact-cPanel-Plugins#20]
Hi,
I get this error after ssh'ing the files to  /iContact-cPanel-Plugins/.
It's probably my lack of command line skills, but I get this response:
```
[root@host /home/bbhstaging]# make
make: *** No targets specified and no makefile found.  Stop.
[root@host /home/bbhstaging]# make install-slack
make: *** No rule to make target `install-slack'.  Stop.
```
Please let me know what you recommend.
Thanks,
Josh

**Comment by troglodyne** [comment]
Presumably you cloned it into bbhstaging then? Or somewhere else?

Running make will only work from the directory you cloned the repository to, so if it is in a subfolder of bbhstaging you should probably cd into the repository's directory before running make.

**Comment by JoshFialkoff** [comment]
You're right @troglodyne! I added it to the root user and it works great. Thanks for this plugin.
One question:
Alerts show up in Slack, but deployment notifications do not.
What do you recommend?

**Comment by troglodyne** [comment]
Hmm, not really sure. Maybe the deployment notifications you are looking for just aren't set to the right priority to send to slack in WHM >> Contact Manager?

You may wanna check there to see if the deployment notifications just aren't setup to send to slack for whatever reason.

Anyways, great to hear that you got it working! I'm going to close out this issue as such.
