### ISSUE TITLE
Everything setup correctly but not working

### ISSUE THREAD

**Issue by hostandname** [troglodyne/iContact-cPanel-Plugins#7]
Hi everyone, is there a way to debug what maybe noticed are not being pushed to slask? it is all setup and integrated.... app enabled for the chatroom and the incoming webhook url but dont seem to sending to the channel

**Comment by troglodyne** [comment]
Generally if there's an error, it will be logged to /usr/local/cpanel/logs/error_log (as is normal with noticies in cPanel & WHM). If it is failing silently, debugging statements would likely need to be added.

**Comment by hostandname** [comment]
Nothing i can see in the log file, what would i need to do to add debugging statements? I am a developer but not familiar with these scripts. Thanks in advance

**Comment by troglodyne** [comment]
Hmm, there should at least be a line in /usr/local/cpanel/logs/error_log *at least* saying something like:
'[2018-01-01 00:00:00 -0500] info [quotacheck] Quota::DiskWarning Notification => info@xxxxxxxxxx
http://some.incoming.webhook/url***** via SLACK [eventimportance => High (1)]`
if it is properly configured.

If not, you'd need to check in WHM >> Contact Manager or /etc/clevels.conf (and make sure it is configured to send notifications for the level you've set Slack notices to get sent).

Hopefully it is just something that simple, but if not, I'll work on adding a debugging test that enables a lot of prints, etc. similar to my XMPP and IRC providers (probably this weekend).

**Comment by troglodyne** [comment]
I've updated the readme with instructions on how to run a full test of the provider (it doesn't have to be on a box with cPanel installed if you just run `make depend` and then run `scripts/generate_testing_configuration.pl` btw).

I just received a message in the slack room I setup to receive message from my incoming webhook URL, so it "works for me" as a test. If you can't get it to send with that test, it should at least throw some sort of error in the test. IF it sends OK in that test (but not in cPanel), then I'd suspect a misconfiguration, likely related to how you've setup something in /etc/clevels.conf.

Let me know how all that goes, I tried to make all this "so simple a soldier could do it," but I'm sure my idea of what constitutes that is probably still too complex for most.

**Comment by troglodyne** [comment]
Closing since no response for a while... feel free to comment with more information on what system you were setting this up on. Things I'd want to know:
* cPanel version
* Notification type we were attempting to send on
* Contents of /var/cpanel/clevels.conf
* Contents of /var/cpanel/icontact_event_importance.json

If I knew all of the above, I could definitively rule out user error (at least).
